'use strict';

const CORRECT = 0;
const WRONG_CONTENT_TYPE = 1;
const WRONG_USERNAME_PASSWORD = 2;
const MISSING_CREDENTIALS = 3;
const WRONG_SERVER = 4;

module.exports = {
  CORRECT: CORRECT,
  WRONG_CONTENT_TYPE: WRONG_CONTENT_TYPE,
  WRONG_USERNAME_PASSWORD: WRONG_USERNAME_PASSWORD,
  MISSING_CREDENTIALS: MISSING_CREDENTIALS,
  WRONG_SERVER: WRONG_SERVER,
};
